use std::fmt::Write as _;

use crate::{Blake3Digest, ContractCatalogV1, FieldTypeV1};

pub(crate) fn rust_constants(
    schema: Blake3Digest,
    registry: Blake3Digest,
    policy: Blake3Digest,
    golden_json: &str,
    golden_hash: Blake3Digest,
    catalog: &ContractCatalogV1,
) -> String {
    let mut output = RUST_TEMPLATE
        .replace("@SCHEMA@", &schema.to_string())
        .replace("@REGISTRY@", &registry.to_string())
        .replace("@POLICY@", &policy.to_string())
        .replace("@GOLDEN_JSON@", golden_json)
        .replace("@GOLDEN_HASH@", &golden_hash.to_string());
    render_rust_records(&mut output, catalog);
    output
}

pub(crate) fn typescript_constants(
    schema: Blake3Digest,
    registry: Blake3Digest,
    policy: Blake3Digest,
    golden_json: &str,
    golden_hash: Blake3Digest,
    catalog: &ContractCatalogV1,
) -> String {
    let encoded_golden = serde_json::to_string(golden_json)
        .expect("a validated canonical JSON string always serializes");
    let mut output = format!(
        "// Generated by: bullet-wire-contract-tool v1alpha1\n\
// Source: contracts/v1alpha1 + policy/v1alpha1\n\
// Command: just contract-generate\n\
// DO NOT EDIT BY HAND.\n\
export const SCHEMA_VERSION = \"v1alpha1\" as const;\n\
export const SCHEMA_BUNDLE_HASH = \"{schema}\" as const;\n\
export const INVARIANT_REGISTRY_HASH = \"{registry}\" as const;\n\
export const POLICY_SNAPSHOT_HASH = \"{policy}\" as const;\n\
export const CANONICAL_GOLDEN_JSON = {encoded_golden} as const;\n\
export const CANONICAL_GOLDEN_HASH = \"{golden_hash}\" as const;\n"
    );
    render_typescript_records(&mut output, catalog);
    output
}

fn render_rust_records(output: &mut String, catalog: &ContractCatalogV1) {
    for record in &catalog.records {
        writeln!(
            output,
            "\n#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]\n\
             #[serde(deny_unknown_fields)]\n\
             pub struct {} {{",
            record.name
        )
        .expect("writing to a String cannot fail");
        for field in &record.fields {
            writeln!(
                output,
                "    pub {}: {},",
                field.name,
                rust_type(field.field_type)
            )
            .expect("writing to a String cannot fail");
        }
        output.push_str("}\n");
    }
}

fn render_typescript_records(output: &mut String, catalog: &ContractCatalogV1) {
    for record in &catalog.records {
        writeln!(output, "\nexport interface {} {{", record.name)
            .expect("writing to a String cannot fail");
        for field in &record.fields {
            writeln!(
                output,
                "  {}: {};",
                field.name,
                typescript_type(field.field_type)
            )
            .expect("writing to a String cannot fail");
        }
        output.push_str("}\n");
    }
}

const fn rust_type(field_type: FieldTypeV1) -> &'static str {
    match field_type {
        FieldTypeV1::String | FieldTypeV1::Identifier | FieldTypeV1::Digest => "String",
        FieldTypeV1::U64 | FieldTypeV1::Timestamp => "u64",
        FieldTypeV1::Boolean => "bool",
        FieldTypeV1::Object => "serde_json::Value",
        FieldTypeV1::StringArray => "Vec<String>",
        FieldTypeV1::ObjectArray => "Vec<serde_json::Value>",
    }
}

const fn typescript_type(field_type: FieldTypeV1) -> &'static str {
    match field_type {
        FieldTypeV1::String | FieldTypeV1::Identifier | FieldTypeV1::Digest => "string",
        FieldTypeV1::U64 | FieldTypeV1::Timestamp => "number",
        FieldTypeV1::Boolean => "boolean",
        FieldTypeV1::Object => "Record<string, unknown>",
        FieldTypeV1::StringArray => "string[]",
        FieldTypeV1::ObjectArray => "Record<string, unknown>[]",
    }
}

const RUST_TEMPLATE: &str = r###"// Generated by: bullet-wire-contract-tool v1alpha1
// Source: contracts/v1alpha1 + policy/v1alpha1
// Command: just contract-generate
// DO NOT EDIT BY HAND.
pub const SCHEMA_VERSION: &str = "v1alpha1";
pub const SCHEMA_BUNDLE_HASH: &str =
    "@SCHEMA@";
pub const INVARIANT_REGISTRY_HASH: &str =
    "@REGISTRY@";
pub const POLICY_SNAPSHOT_HASH: &str =
    "@POLICY@";
pub const CANONICAL_GOLDEN_JSON: &str = r##"@GOLDEN_JSON@"##;
pub const CANONICAL_GOLDEN_HASH: &str =
    "@GOLDEN_HASH@";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PinnedContract {
    SchemaBundle,
    InvariantRegistry,
    PolicySnapshot,
    CanonicalGolden,
}

impl PinnedContract {
    fn identity(self) -> (&'static str, &'static str) {
        match self {
            Self::SchemaBundle => ("schema.bundle", SCHEMA_BUNDLE_HASH),
            Self::InvariantRegistry => ("invariant.registry", INVARIANT_REGISTRY_HASH),
            Self::PolicySnapshot => ("policy.snapshot", POLICY_SNAPSHOT_HASH),
            Self::CanonicalGolden => ("golden.cross-language", CANONICAL_GOLDEN_HASH),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ContractPinError {
    document: &'static str,
}

impl ContractPinError {
    #[must_use]
    pub const fn reason_code(&self) -> &'static str {
        "UNPINNED_CONTRACT"
    }

    #[must_use]
    pub const fn document(&self) -> &'static str {
        self.document
    }
}

impl std::fmt::Display for ContractPinError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            formatter,
            "{} bytes do not match the pinned identity",
            self.document
        )
    }
}

impl std::error::Error for ContractPinError {}

pub fn verify_pinned_contract(
    contract: PinnedContract,
    bytes: &[u8],
) -> Result<(), ContractPinError> {
    let (domain, expected) = contract.identity();
    let mut hasher = blake3::Hasher::new();
    hasher.update(b"bullet-wire.v1\0");
    update_frame(&mut hasher, domain.as_bytes());
    update_frame(&mut hasher, bytes);
    let actual = hasher.finalize().to_hex();
    if actual.as_str() == expected {
        Ok(())
    } else {
        Err(ContractPinError { document: domain })
    }
}

fn update_frame(hasher: &mut blake3::Hasher, bytes: &[u8]) {
    hasher.update(&(bytes.len() as u64).to_le_bytes());
    hasher.update(bytes);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn golden_pin_rejects_any_byte_or_domain_change() {
        verify_pinned_contract(
            PinnedContract::CanonicalGolden,
            CANONICAL_GOLDEN_JSON.as_bytes(),
        )
        .unwrap();

        let mut changed = CANONICAL_GOLDEN_JSON.as_bytes().to_vec();
        changed.push(b' ');
        let error = verify_pinned_contract(PinnedContract::CanonicalGolden, &changed).unwrap_err();
        assert_eq!(error.reason_code(), "UNPINNED_CONTRACT");
        assert_eq!(error.document(), "golden.cross-language");
        assert!(verify_pinned_contract(
            PinnedContract::SchemaBundle,
            CANONICAL_GOLDEN_JSON.as_bytes(),
        )
        .is_err());
    }
}
"###;
