//! Deterministic Markdown rendering of the release truth page.

use std::fmt::Write as _;

use super::{
    facts::{Facts, Mechanical, Register, Variant},
    rows::{self, ClaimRow, UngatedRow},
};
use crate::{
    check::model::{CheckReport, GateResult, GateStatus},
    coord::CoordError,
};

const PROJECTION: &str =
    "PROJECTION — rendered from machine facts; this page holds no release authority";
pub(super) const UNGATED_HEADING: &str = "## Blocking but not a release gate";
pub(super) const CROSSWALK_HEADING: &str = "## Product-gap crosswalk";

pub(super) fn render(facts: &Facts, report: &CheckReport) -> Result<String, CoordError> {
    let mut out = String::new();
    header(&mut out, facts, report);
    subjects(&mut out, facts);
    lock(&mut out, facts);
    truths(&mut out, facts, report);
    gates(&mut out, report)?;
    crosswalk(&mut out, facts, report);
    ungated(&mut out)?;
    excluded(&mut out);
    freshness(&mut out, facts);
    while out.ends_with('\n') {
        out.pop();
    }
    Ok(out)
}

fn header(out: &mut String, facts: &Facts, report: &CheckReport) {
    let (variant, variant_note) = match facts.variant {
        Variant::Live => (
            "--report",
            "LIVE — machine-local subjects, absolute paths, and mtimes are included",
        ),
        Variant::Portable => (
            "--report --portable",
            "PORTABLE — machine-local subjects, absolute paths, and mtimes are excluded; reproducible from a fresh hub-only checkout",
        ),
    };
    let _ = writeln!(
        out,
        "<!-- Generated by: bullet-family check release {variant} -->\n<!-- Source: src/check/prerequisites.rs + src/check/truth/rows.rs + family.lock + repos.manifest.toml + docs/release.md + docs/assurance/product-gaps.md -->\n<!-- Command: just release-truth -->\n<!-- DO NOT EDIT BY HAND. -->\n\n# Release truth\n\nRELEASE DECISION: {}\n",
        report.status().as_str()
    );
    let head = facts.hub_head_committed_at.as_deref().map_or_else(
        || "hub HEAD committer date not read".to_owned(),
        |date| format!("hub HEAD committed {date} (source: git log -1 --format=%cI)"),
    );
    let reviewed = facts.release_index.last_reviewed.as_deref().map_or_else(
        || {
            format!(
                "`{}` has no `Last reviewed:` line",
                super::facts::RELEASE_INDEX
            )
        },
        |date| format!("`{}` Last reviewed: {date}", super::facts::RELEASE_INDEX),
    );
    let _ = writeln!(out, "| Field | Value |\n| --- | --- |");
    let _ = writeln!(
        out,
        "| as_of | {head}; {reviewed}; no wall clock was read |"
    );
    let _ = writeln!(
        out,
        "| source | `bullet-family {}` static release inventory, check report schema {}, tier {}, {} gates |",
        env!("CARGO_PKG_VERSION"),
        report.schema_version(),
        report.tier().as_str(),
        report.gates().len()
    );
    let _ = writeln!(
        out,
        "| scope | the {} registered release gates of the four-repository Bullet Farm family, each mapped to its product gap G-id from `{}`; gap {} is this inventory itself; nothing outside the catalog is counted |",
        report.gates().len(),
        super::facts::PRODUCT_GAP_REGISTER,
        rows::INVENTORY_GAP
    );
    let _ = writeln!(
        out,
        "| freshness | every input is identified by digest in the Freshness section; a gate row changes only when its catalog entry, its claim row, the register crosswalk, or a receipt changes |"
    );
    let _ = writeln!(out, "| projection | {PROJECTION} |");
    let _ = writeln!(out, "| variant | {variant_note} |");
    if let Some(hub) = &facts.hub_root {
        let _ = writeln!(out, "| hub | `{hub}` |");
    }
    out.push('\n');
}

fn subjects(out: &mut String, facts: &Facts) {
    let _ = writeln!(
        out,
        "## Repository subjects\n\n| Repository | Commit | Tree | Checkout |\n| --- | --- | --- | --- |"
    );
    for subject in &facts.subjects {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            subject.name,
            code_or_unknown(subject.commit.as_deref()),
            code_or_unknown(subject.tree.as_deref()),
            subject.checkout
        );
    }
    out.push('\n');
}

fn lock(out: &mut String, facts: &Facts) {
    let _ = writeln!(out, "## Family lock\n\n| Field | Value |\n| --- | --- |");
    match &facts.lock {
        Err(error) => {
            let _ = writeln!(out, "| schema | UNKNOWN ({error}) |\n| tag | UNKNOWN |");
            let _ = writeln!(out, "| binds current HEADs | UNKNOWN (lock unreadable) |");
        }
        Ok(lock) => {
            let install = if lock.installable {
                "strict schema-3 lock; install authority still requires signed subjects"
            } else {
                "diagnostic-only; every installer path refuses it by design"
            };
            let _ = writeln!(out, "| schema | {} ({install}) |", lock.schema_version);
            let _ = writeln!(out, "| tag | `{}` |", lock.tag);
            let _ = writeln!(out, "| binds current HEADs | {} |", binding(facts, lock));
        }
    }
    out.push('\n');
}

fn binding(facts: &Facts, lock: &crate::doctor::LockSummary) -> String {
    if facts.variant == Variant::Portable {
        return "UNKNOWN (portable variant does not read checkouts)".to_owned();
    }
    let mut mismatches = Vec::new();
    for (name, locked) in &lock.members {
        let live = facts
            .subjects
            .iter()
            .find(|subject| subject.name == name)
            .and_then(|subject| subject.commit.as_deref());
        match live {
            Some(commit) if commit.split_once(':').map(|pair| pair.1) == Some(locked) => {}
            Some(commit) => mismatches.push(format!("{name} locked `{locked}` HEAD `{commit}`")),
            None => mismatches.push(format!("{name} locked `{locked}` HEAD UNKNOWN")),
        }
    }
    if mismatches.is_empty() {
        "YES — every locked member commit equals its current HEAD".to_owned()
    } else {
        format!("NO — {}", mismatches.join("; "))
    }
}

fn receipted(report: &CheckReport) -> usize {
    report
        .gates()
        .iter()
        .filter(|gate| gate.status() == GateStatus::Pass)
        .count()
}

fn truths(out: &mut String, facts: &Facts, report: &CheckReport) {
    let receipted = receipted(report);
    let total = report.gates().len();
    let _ = writeln!(
        out,
        "## Five truths, never conflated\n\n| Truth | Status | Source | Scope |\n| --- | --- | --- | --- |"
    );
    for fact in &facts.mechanical {
        let status = match &fact.outcome {
            Mechanical::NotRead => {
                "NOT RUN (portable variant does not read machine-local check reports)".to_owned()
            }
            Mechanical::Absent => "NOT RUN (no generated check report)".to_owned(),
            Mechanical::Unreadable(reason) => format!("NOT RUN (unreadable: {reason})"),
            Mechanical::Stale {
                status,
                gates,
                mismatch,
            } => {
                format!(
                    "STALE — {status} over {gates} gates recorded against other subjects ({mismatch})"
                )
            }
            Mechanical::Fresh { status, gates } => {
                format!("{status} — {gates} gates on current HEADs")
            }
        };
        let _ = writeln!(
            out,
            "| Mechanical gates ({}) | {status} | `{}` written by `bullet-family check {} --json` | fixed {} command catalog; a pass here is not release readiness |",
            fact.tier, fact.path, fact.tier, fact.tier
        );
    }
    let _ = writeln!(
        out,
        "| Evidence completeness | {receipted} of {total} receipted | static negative inventory in `src/check/prerequisites.rs`; only `release.rust-msrv-1-95` admits an external receipt | the {total} registered release gates |"
    );
    let review = if receipted == total {
        "OPEN — every gate is receipted; human release review may begin"
    } else {
        "HOLD — no receipt exists to review"
    };
    let _ = writeln!(
        out,
        "| Release review | {review} | this page; no reviewer record exists | human verification of receipted gates |"
    );
    let _ = writeln!(
        out,
        "| Deployment match | N/A — pre-release; nothing is deployed | no deployment record exists | deployed SHA versus reviewed integration subject |"
    );
    let _ = writeln!(
        out,
        "| Post-deploy survival | NOT ESTABLISHED | no deployment observation exists | required observations after a deployment |"
    );
    out.push('\n');
}

fn gates(out: &mut String, report: &CheckReport) -> Result<(), CoordError> {
    let unproved = report.gates().len() - receipted(report);
    let _ = writeln!(
        out,
        "## Gates ({unproved} of {} unproved)\n",
        report.gates().len()
    );
    for (index, gate) in report.gates().iter().enumerate() {
        let row = rows::find(gate.id()).ok_or_else(|| {
            CoordError::new(
                "RELEASE_TRUTH_ROW_MISSING",
                format!("no claim row for gate {}", gate.id()),
            )
        })?;
        gate_row(out, index + 1, gate, row)?;
    }
    Ok(())
}

fn reads_closed(id: &str, texts: &[&str]) -> Result<(), CoordError> {
    if texts.iter().any(|text| rows::contains_closed_word(text)) {
        return Err(CoordError::new(
            "RELEASE_TRUTH_CLAIM_READS_CLOSED",
            format!(
                "{id} is unreceipted but its row uses one of {:?}",
                rows::CLOSED_WORDS
            ),
        ));
    }
    Ok(())
}

fn gate_row(
    out: &mut String,
    number: usize,
    gate: &GateResult,
    row: &ClaimRow,
) -> Result<(), CoordError> {
    let receipted = gate.status() == GateStatus::Pass;
    if !receipted {
        reads_closed(gate.id(), &row.texts())?;
    }
    let headline = if receipted {
        format!("Receipted: {}", gate.detail())
    } else {
        row.claim.to_owned()
    };
    let _ = writeln!(
        out,
        "{number}. **{headline}** — `{}` {}",
        gate.id(),
        gate.status().as_str()
    );
    let _ = writeln!(out, "   - Product gap: {}", row.gap_ids.join(", "));
    let _ = writeln!(out, "   - Why it matters: {}", row.why);
    let _ = writeln!(out, "   - Acceptance: {}", row.acceptance);
    let _ = writeln!(out, "   - Evidence class: {}_PROOF", gate.class().as_str());
    let evidence = match gate.status() {
        GateStatus::Pass => gate.detail().to_owned(),
        GateStatus::Fail => format!(
            "REJECTED — {}; exists but does not count: {}",
            gate.detail(),
            row.exists
        ),
        _ => format!(
            "NONE — {}; exists but does not count: {}",
            gate.detail(),
            row.exists
        ),
    };
    let _ = writeln!(out, "   - Current evidence: {evidence}");
    let _ = writeln!(out, "   - Owner: {}", row.owner.render());
    let _ = writeln!(out, "   - Next command: {}", row.next.render());
    let _ = writeln!(out, "   - Release-blocking: yes");
    Ok(())
}

fn crosswalk(out: &mut String, facts: &Facts, report: &CheckReport) {
    let _ = writeln!(
        out,
        "\n{CROSSWALK_HEADING}\n\nEvery G-id of `{}` is answered exactly once: by the gate rows that name it, by the ungated section below, or by this inventory. Titles are compiled; the crosswalk rows are read from the register and compared here.\n\n| Gap | Title | Answered by |\n| --- | --- | --- |",
        super::facts::PRODUCT_GAP_REGISTER
    );
    for &(gap, title) in rows::PRODUCT_GAPS {
        let gates = rows::gates_for(gap);
        let answer = if gap == rows::INVENTORY_GAP {
            format!(
                "this inventory — {} gates, {} receipted (`bullet-family check release --json`)",
                report.gates().len(),
                receipted(report)
            )
        } else if !gates.is_empty() {
            gates
                .iter()
                .map(|id| format!("`{id}`"))
                .collect::<Vec<_>>()
                .join(", ")
        } else if rows::ungated_for(gap).is_some() {
            "ungated — see “Blocking but not a release gate” below".to_owned()
        } else {
            "UNANSWERED".to_owned()
        };
        let _ = writeln!(out, "| {gap} | {title} | {answer} |");
    }
    let _ = writeln!(
        out,
        "\nAgreement with `{}`: {}",
        super::facts::PRODUCT_GAP_REGISTER,
        agreement(&facts.register)
    );
}

fn agreement(register: &Register) -> String {
    let table = match register {
        Register::Absent => {
            return "UNKNOWN — the register is absent from this checkout".to_owned();
        }
        Register::Unparsed(reason) => return format!("UNKNOWN — register unparsed: {reason}"),
        Register::Read(table) => table,
    };
    let diffs = rows::crosswalk_diffs(table);
    if diffs.is_empty() {
        format!(
            "YES — all {} crosswalk rows and the G-id list agree",
            table.gates.len()
        )
    } else {
        format!("NO — {}", diffs.join("; "))
    }
}

fn ungated(out: &mut String) -> Result<(), CoordError> {
    let _ = writeln!(
        out,
        "\n{UNGATED_HEADING}\n\nProduct gaps with no `release.*` id. Each row says which gate it blocks through; none can be receipted here, and each is listed so that no G-id is invisible to machine output.\n"
    );
    for (index, row) in rows::UNGATED.iter().enumerate() {
        ungated_row(out, index + 1, row)?;
    }
    Ok(())
}

fn ungated_row(out: &mut String, number: usize, row: &UngatedRow) -> Result<(), CoordError> {
    reads_closed(row.gap_id, &row.texts())?;
    let title = rows::gap_title(row.gap_id).unwrap_or("UNKNOWN GAP");
    let _ = writeln!(out, "{number}. **{}** — {} {title}", row.claim, row.gap_id);
    let _ = writeln!(out, "   - Why it matters: {}", row.why);
    let _ = writeln!(out, "   - Acceptance: {}", row.acceptance);
    let _ = writeln!(out, "   - Evidence class: {}_PROOF", row.class.as_str());
    let _ = writeln!(out, "   - Current evidence: {}", row.evidence);
    let _ = writeln!(out, "   - Owner: {}", row.owner.render());
    let _ = writeln!(out, "   - Next command: {}", row.next.render());
    let _ = writeln!(out, "   - Release-blocking: {}", row.blocking);
    Ok(())
}

fn excluded(out: &mut String) {
    let _ = writeln!(
        out,
        "\n## Excluded from this decision\n\n\
- Synthetic receipts, including the `required.demo-component` simulator lane: SYNTHETIC_PROOF never counts toward a release gate.\n\
- Simulator runs, fixture-only policies, and the fixture-only live-enabled v1alpha2 policy: none is an operator ratification.\n\
- Prose: `docs/release.md`, `docs/assurance/product-gaps.md`, `docs/assurance/v1-closure-plan.md`, ADRs, changelog, and coordination chat describe evidence; they are not evidence.\n\
- Component receipts named in `docs/release.md` and in the “exists but does not count” text above: COMPONENT_PROOF for one crate or surface, never transaction, live, or release evidence.\n\
- The archived 2026-08-24 live demonstration receipt at the family root `.l7-bundle/`: incident evidence only (`transaction_gate_eligible: false`); it is not counted.\n\
- Any mechanical gate result recorded against subjects other than the current HEADs (STALE above).\n\
- Reviewer checkmarks, browser-local marks, exit codes, model statements, pushed branches, and pull requests."
    );
}

fn freshness(out: &mut String, facts: &Facts) {
    let _ = writeln!(
        out,
        "\n## Freshness\n\n| Input | Path | Identity | mtime (unix seconds) |\n| --- | --- | --- | --- |"
    );
    for input in &facts.inputs {
        let mtime = match (&input.mtime, facts.variant) {
            (Some(mtime), _) => mtime.clone(),
            (None, Variant::Portable) => "excluded (portable variant)".to_owned(),
            (None, Variant::Live) => "—".to_owned(),
        };
        let _ = writeln!(
            out,
            "| {} | `{}` | {} | {mtime} |",
            input.label, input.path, input.identity
        );
    }
    let _ = writeln!(
        out,
        "| gate catalog | `src/check/prerequisites.rs` (compiled into `bullet-family {}`) | check report schema {} | — |",
        env!("CARGO_PKG_VERSION"),
        crate::check::model::CHECK_REPORT_SCHEMA_VERSION
    );
    let _ = writeln!(
        out,
        "| claim rows | `src/check/truth/rows.rs` + `rows/gates.rs` + `rows/ungated.rs` (compiled into `bullet-family {}`) | {} gate rows + {} ungated rows over {} G-ids | — |",
        env!("CARGO_PKG_VERSION"),
        rows::ROWS.len(),
        rows::UNGATED.len(),
        rows::PRODUCT_GAPS.len()
    );
}

fn code_or_unknown(value: Option<&str>) -> String {
    value.map_or_else(|| "UNKNOWN".to_owned(), |value| format!("`{value}`"))
}
