//! Release truth (shift brief): the exact claims that remain unproved, rendered
//! from machine facts only. The page is a projection; it never changes a gate.

mod facts;
mod render;
mod rows;

use std::path::Path;

use super::model::CheckReport;
use crate::coord::CoordError;
pub(super) use facts::Variant;

pub(super) fn render(
    hub: &Path,
    report: &CheckReport,
    variant: Variant,
) -> Result<String, CoordError> {
    let facts = facts::gather(hub, variant);
    render::render(&facts, report)
}

#[cfg(test)]
mod tests {
    use super::{
        facts::{Facts, InputFact, Mechanical, MechanicalFact, ReleaseIndexFact, SubjectFact},
        *,
    };
    use crate::{check::prerequisites, doctor::LockSummary};

    fn synthetic(variant: Variant) -> Facts {
        let live = variant == Variant::Live;
        Facts {
            variant,
            hub_root: live.then(|| "/fixture/bullet-farm".to_owned()),
            subjects: vec![
                SubjectFact {
                    name: "bullet-farm",
                    commit: Some(format!("sha1:{}", "a".repeat(40))),
                    tree: Some(format!("sha1:{}", "b".repeat(40))),
                    checkout: "clean".to_owned(),
                },
                SubjectFact {
                    name: "bullet-kernel",
                    commit: None,
                    tree: None,
                    checkout: "absent".to_owned(),
                },
            ],
            hub_head_committed_at: live.then(|| "2026-01-02T03:04:05+00:00".to_owned()),
            lock: Ok(LockSummary {
                schema_version: "2".to_owned(),
                tag: "v0.0.0-fixture".to_owned(),
                installable: false,
                members: vec![
                    ("bullet-farm".to_owned(), "a".repeat(40)),
                    ("bullet-kernel".to_owned(), "c".repeat(40)),
                ],
            }),
            release_index: ReleaseIndexFact {
                status: Some("BLOCKED".to_owned()),
                last_reviewed: Some("2026-01-01".to_owned()),
            },
            mechanical: vec![
                MechanicalFact {
                    tier: "fast",
                    path: ".bullet-family/check-fast.json",
                    outcome: Mechanical::Stale {
                        status: "PASS".to_owned(),
                        gates: 7,
                        mismatch: "bullet-farm recorded sha1:0, HEAD sha1:a".to_owned(),
                    },
                },
                MechanicalFact {
                    tier: "required",
                    path: ".bullet-family/check-required.json",
                    outcome: Mechanical::Absent,
                },
            ],
            inputs: vec![InputFact {
                label: "family lock",
                path: "family.lock",
                identity: format!("blake3:{}", "d".repeat(64)),
                mtime: live.then(|| "1700000000".to_owned()),
            }],
        }
    }

    #[test]
    fn rendering_is_deterministic_and_keeps_the_five_truths_apart() {
        let report = prerequisites::report_release().unwrap();
        for variant in [Variant::Live, Variant::Portable] {
            let facts = synthetic(variant);
            let first = render::render(&facts, &report).unwrap();
            let second = render::render(&facts, &report).unwrap();
            assert_eq!(first, second);
            assert!(first.starts_with("<!-- Generated by: bullet-family check release --report"));
            assert!(first.contains("\nRELEASE DECISION: BLOCKED\n"));
            for truth in [
                "| Mechanical gates (fast) | STALE — PASS over 7 gates",
                "| Mechanical gates (required) | NOT RUN",
                "| Evidence completeness | 0 of 26 receipted |",
                "| Release review | HOLD",
                "| Deployment match | N/A",
                "| Post-deploy survival | NOT ESTABLISHED |",
            ] {
                assert!(first.contains(truth), "{variant:?} lacks {truth}");
            }
            assert!(first.contains("| bullet-kernel | UNKNOWN | UNKNOWN | absent |"));
            assert!(first.contains("| tag | `v0.0.0-fixture` |"));
            assert!(!first.ends_with('\n'));
            assert_eq!(first.matches("   - Release-blocking: yes\n").count(), 26);
        }
        let live = render::render(&synthetic(Variant::Live), &report).unwrap();
        assert!(live.contains("| hub | `/fixture/bullet-farm` |"));
        assert!(live.contains("NO — bullet-kernel locked `ccc"));
        assert!(live.contains("hub HEAD committed 2026-01-02T03:04:05+00:00"));
        let portable = render::render(&synthetic(Variant::Portable), &report).unwrap();
        assert!(!portable.contains("/fixture/"));
        assert!(!portable.contains("1700000000"));
        assert!(portable.contains("| binds current HEADs | UNKNOWN (portable variant"));
    }

    #[test]
    fn rendered_claim_blocks_never_read_as_closed_while_unreceipted() {
        let report = prerequisites::report_release().unwrap();
        let page = render::render(&synthetic(Variant::Portable), &report).unwrap();
        let (_, gates) = page.split_once("## Gates").unwrap();
        let (gates, _) = gates.split_once("## Excluded").unwrap();
        let mut blocks = 0;
        for line in gates.lines().filter(|line| {
            line.contains("**")
                || line.contains("- Why it matters:")
                || line.contains("- Acceptance:")
        }) {
            assert!(
                !rows::contains_closed_word(line),
                "closed vocabulary: {line}"
            );
            blocks += 1;
        }
        assert_eq!(blocks, 26 * 3);
    }
}
